definitions:
  Controller.Response:
    properties:
      data:
        $ref: '#/definitions/Controller.UserResponse'
      length:
        type: integer
      response_id:
        type: string
      status:
        type: integer
    type: object
  Controller.UserRequest:
    properties:
      name:
        type: string
      surname:
        type: string
    type: object
  Controller.UserResponse:
    properties:
      id:
        type: string
      name:
        type: string
      request_date:
        type: string
      surname:
        type: string
    type: object
info:
  contact: {}
  description: Realized GET and POST methods
  title: Test Task
paths:
  /requests:
    get:
      consumes:
      - application/json
      description: get all requests
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Controller.UserRequest'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: getUsers
      tags:
      - Requests
  /responses:
    get:
      consumes:
      - application/json
      description: get all responses
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Controller.Response'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: getResponses
      tags:
      - Responses
  /user:
    post:
      consumes:
      - application/json
      description: post a new user
      parameters:
      - description: User
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/Controller.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Controller.UserResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: postUser
      tags:
      - User
swagger: "2.0"
